[project]
name = "performance_scorecard"
authors = [
    { name = "Antigravity", email = "bot@example.com"}
]
description = "Performance Management App for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # Add dependencies here if any
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench]
is-frappe-app = true
