frappe.pages['risk-heat-map'].on_page_load = function (wrapper) {
    var page = frappe.ui.make_app_page({
        parent: wrapper,
        title: 'Risk Heat Map',
        single_column: true
    });

    page.set_primary_action('Refresh', function () {
        load_heat_map(page);
    });

    // Add CSS
    frappe.require([
        '/assets/performance_scorecard/css/performance_dashboard.css',
        '/assets/performance_scorecard/css/risk_heat_map.css'
    ], () => {
        load_heat_map(page);
    });
}

function load_heat_map(page) {
    $(page.body).empty();
    $(page.body).append('<div class="dashboard-content">Loading...</div>');

    frappe.call({
        method: "performance_scorecard.performance_scorecard.page.risk_heat_map.risk_heat_map.get_risk_matrix_data",
        callback: function (r) {
            if (r.message) {
                render_page(page, r.message);
            }
        }
    });
}

function render_page(page, data) {
    $(page.body).empty();

    const company = "Norwa Performance Center";
    const fullname = frappe.session.user_fullname;

    let html = `
        <div class="dashboard-container">
            <!-- Sidebar -->
            <div class="dashboard-sidebar">
                <div class="sidebar-header">
                    <h3 style="color:white; margin:0;">${company}</h3>
                </div>
                <ul class="sidebar-menu">
                    <li data-section="home"><i class="fa fa-home"></i> Home</li>
                    <li data-section="strategy-plans"><i class="fa fa-list"></i> Strategy Plans</li>
                    <li data-section="strategy-maps"><i class="fa fa-sitemap"></i> Strategy Maps</li>
                    <li class="active" data-section="risk-management"><i class="fa fa-exclamation-triangle"></i> Risk Management</li>
                    <li data-section="dashboards"><i class="fa fa-tachometer"></i> Dashboards</li>
                    <li data-section="reports"><i class="fa fa-file-text"></i> Reports</li>
                    <li data-section="administration"><i class="fa fa-cog"></i> Administration</li>
                </ul>
                <div class="user-profile">
                    <div class="user-avatar"></div>
                    <div>
                        <div style="font-weight:bold; font-size:12px;">${fullname}</div>
                        <div style="font-size:10px; color:#a0aec0;">User</div>
                    </div>
                </div>
            </div>

            <!-- Main Content -->
            <div class="dashboard-main">
                <div class="dashboard-header">
                    <div class="page-title">Risk Heat Map (ISO 31000)</div>
                    <div>
                        <button class="btn btn-default btn-sm" id="btn-back-to-dash" style="margin-right: 10px;">Back to Dashboard</button>
                        <i class="fa fa-user-circle" style="font-size:24px; color:#e53e3e;"></i>
                    </div>
                </div>

                <div class="risk-matrix-container">
                    <div class="matrix-wrapper">
                        <div class="y-axis-label">Impact (Consequence)</div>
                        <div class="matrix-grid" id="risk-matrix-grid">
                            <!-- Grid generated by JS -->
                        </div>
                        <div class="x-axis-label">Likelihood (Probability)</div>
                    </div>
                    <div class="risk-details-panel" id="risk-details-panel">
                        <div class="text-muted text-center" style="padding-top: 100px;">
                            <i class="fa fa-mouse-pointer" style="font-size: 40px; margin-bottom: 10px; opacity: 0.3;"></i><br>
                            Select a cell to view risks
                        </div>
                    </div>
                </div>
            </div>
        </div>
    `;

    $(page.body).append(html);

    render_matrix(data);
    bind_sidebar(page);

    $('#btn-back-to-dash').click(() => frappe.set_route('risk-dashboard'));
}

function render_matrix(data) {
    let $grid = $('#risk-matrix-grid');
    $grid.empty();

    // 5x5 Grid (Impact 5->1 (Rows), Likelihood 1->5 (Cols))
    for (let impact = 5; impact >= 1; impact--) {
        for (let likelihood = 1; likelihood <= 5; likelihood++) {
            let key = `${likelihood}-${impact}`;
            let risks = data[key] || [];
            let count = risks.length;
            let score = likelihood * impact;

            let colorClass = get_cell_color(score);

            let $cell = $(`
                <div class="matrix-cell ${colorClass}" data-key="${key}">
                    <div class="cell-score">${score}</div>
                    ${count > 0 ? `<div class="risk-count">${count}</div>` : ''}
                </div>
            `);

            $cell.click(function () {
                $('.matrix-cell').removeClass('active');
                $(this).addClass('active');
                show_risks(risks, likelihood, impact);
            });

            $grid.append($cell);
        }
    }
}

function get_cell_color(score) {
    if (score >= 15) return 'cell-red';
    if (score >= 6) return 'cell-yellow';
    return 'cell-green';
}

function show_risks(risks, l, i) {
    let $panel = $('#risk-details-panel');
    $panel.empty().hide().fadeIn();

    $panel.append(`<h4>Risks at L:${l} x I:${i}</h4>`);

    if (risks.length === 0) {
        $panel.append('<div class="empty-state">No risks found for this probability/impact combination.</div>');
        return;
    }

    let html = '<div class="list-group">';
    risks.forEach(risk => {
        html += `
            <a href="/app/risk-register/${risk.name}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1" style="font-weight: 700; color: #2d3748;">${risk.risk_title}</h5>
                    <span class="badge ${risk.risk_level === 'High' ? 'badge-red' : (risk.risk_level === 'Medium' ? 'badge-yellow' : 'badge-green')}">${risk.risk_level}</span>
                </div>
                <p class="mb-1 text-muted small">${risk.risk_category || 'General'} | Owner: ${risk.risk_owner || 'Unassigned'}</p>
                <small class="text-primary">ID: ${risk.name}</small>
            </a>
        `;
    });
    html += '</div>';

    $panel.append(html);
}

function bind_sidebar(page) {
    const $body = $(page.body);
    $body.find(".sidebar-menu li").on("click", function () {
        const section = $(this).data("section");
        if (section === "home") {
            frappe.set_route("performance-dashboard");
        } else if (section === "risk-management") {
            frappe.set_route("risk-dashboard");
        } else if (section === "administration") {
            frappe.set_route("Form", "Performance Settings");
        } else {
            frappe.set_route("performance-dashboard");
        }
    });
}
