frappe.pages['risk-heat-map'].on_page_load = function (wrapper) {
    var page = frappe.ui.make_app_page({
        parent: wrapper,
        title: 'Risk Heat Map',
        single_column: true
    });

    page.set_primary_action('Refresh', function () {
        load_heat_map(page);
    });

    // Add CSS
    frappe.require('/assets/performance_scorecard/css/risk_heat_map.css');

    $(page.body).append(`
        <div class="risk-matrix-container">
            <div class="matrix-wrapper">
                <div class="y-axis-label">Impact</div>
                <div class="matrix-grid">
                    <!-- Grid generated by JS -->
                </div>
                <div class="x-axis-label">Likelihood</div>
            </div>
            <div class="risk-details-panel">
                <div class="text-muted text-center" style="padding-top: 100px;">
                    Select a cell to view risks
                </div>
            </div>
        </div>
    `);

    load_heat_map(page);
}

function load_heat_map(page) {
    frappe.call({
        method: "performance_scorecard.performance_scorecard.page.risk_heat_map.risk_heat_map.get_risk_matrix_data",
        callback: function (r) {
            if (r.message) {
                render_matrix(r.message);
            }
        }
    });
}

function render_matrix(data) {
    let $grid = $('.matrix-grid');
    $grid.empty();

    // 5x5 Grid (Impact 5->1 (Rows), Likelihood 1->5 (Cols))
    // We render rows from top (Impact 5) to bottom (Impact 1)

    for (let impact = 5; impact >= 1; impact--) {
        for (let likelihood = 1; likelihood <= 5; likelihood++) {
            let key = `${likelihood}-${impact}`;
            let risks = data[key] || [];
            let count = risks.length;
            let score = likelihood * impact;

            let colorClass = get_cell_color(score);

            let $cell = $(`
                <div class="matrix-cell ${colorClass}" data-key="${key}">
                    <div class="cell-score">${score}</div>
                    ${count > 0 ? `<div class="risk-count">${count}</div>` : ''}
                </div>
            `);

            $cell.click(function () {
                $('.matrix-cell').removeClass('active');
                $(this).addClass('active');
                show_risks(risks, likelihood, impact);
            });

            $grid.append($cell);
        }
    }
}

function get_cell_color(score) {
    if (score >= 15) return 'cell-red';
    if (score >= 6) return 'cell-yellow';
    return 'cell-green';
}

function show_risks(risks, l, i) {
    let $panel = $('.risk-details-panel');
    $panel.empty();

    $panel.append(`<h4>Risks (L:${l} x I:${i})</h4>`);

    if (risks.length === 0) {
        $panel.append('<p class="text-muted">No risks in this category.</p>');
        return;
    }

    let html = '<div class="list-group">';
    risks.forEach(risk => {
        html += `
            <a href="/app/risk-register/${risk.name}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">${risk.risk_title}</h5>
                    <small>${risk.risk_level}</small>
                </div>
                <p class="mb-1 text-muted small">${risk.name}</p>
            </a>
        `;
    });
    html += '</div>';

    $panel.append(html);
}
